# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
# (Required) Acceptable Values: Component, Resource, System
# Use `Component` unless you know how backstage works and what the other kinds mean.
kind: Component
metadata:
  name: 'xblock-sdk'
  description: "A Workbench for developing xblocks and some sample xblocks."
  links:
    - url: "https://edx.readthedocs.io/projects/xblock-tutorial/en/latest/sdk/get_started_sdk.html"
      title: "Documentation"
      # Backstage uses the MaterialUI Icon Set.
      # https://mui.com/material-ui/material-icons/
      # The value will be the name of the icon.
      icon: "Article"
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: "feanil"
spec:

  # (Required) This can be a group (`group:<github_group_name>`) or a user (`user:<github_username>`).
  # Don't forget the "user:" or "group:" prefix. Groups must be GitHub team
  # names in the openedx GitHub organization: https://github.com/orgs/openedx/teams
  #
  # If you need a new team created, create an issue with Axim engineering:
  # https://github.com/openedx/axim-engineering/issues/new/choose
  owner: group:axim-engineering

  # (Required) Acceptable Type Values: service, website, library
  type: 'xblock'

  # (Required) Acceptable Lifecycle Values: experimental, production, deprecated
  lifecycle: 'production'
