# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XBlockState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, choices=[('usage', 'usage'), ('definition', 'definition'), ('type', 'type'), ('all', 'all'), ('parent', 'parent'), ('children', 'children')], db_index=True, max_length=50, null=True)),
                ('scope_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name=b'Scope ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name=b'User ID')),
                ('scenario', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('state', models.TextField(default=b'{}')),
            ],
            options={
                'ordering': ['scope_id', 'scope', 'user_id'],
                'verbose_name': 'XBlock State',
                'verbose_name_plural': 'XBlock State',
            },
        ),
    ]
