name: Publish package to PyPi

on:
  push:
    tags:
      - '*'

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
