name: Upgrade Requirements

on:
  schedule:
    # will start the job at Midnight UTC every Sunday
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: 'master'

jobs:
  call-upgrade-python-requirements-workflow:
    with:
       branch: ${{ github.event.inputs.branch }}
       team_reviewers: "axim-engineering"
    secrets:
       requirements_bot_github_token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}
       requirements_bot_github_email: ${{ secrets.REQUIREMENTS_BOT_GITHUB_EMAIL }}
       edx_smtp_username: ${{ secrets.EDX_SMTP_USERNAME }}
       edx_smtp_password: ${{ secrets.EDX_SMTP_PASSWORD }}
    uses: openedx/.github/.github/workflows/upgrade-python-requirements.yml@master
   
  tag-axim-team-for-review:     
    name: Tag Axim Team for review
    runs-on: ubuntu-latest
    steps:
      - name: Mention aximprovements team
        uses: actions/github-script@v4         
        with:           
          script: |
              const teamName = "openedx/axim-aximprovements";
              const prNumber = context.payload.pull_request.number;
              const comment = `@${teamName} New pull request (#${prNumber})for review
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: comment
              });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
